### ISSUE TITLE
Latest eID cannot be read it seems, no nuget package of latest version

### ISSUE THREAD

**Issue by COBRASoft5** [perevoznyk/swelio-sdk#10]
Hi,

It seems the latest eID cards cannot be read with v1.8.0 (nuget). I see there's a new version on Github, but no nuget package available for it (v1.8.5).

Will this new version support latest eID cards and will you create a nuget package for it please?

Thanks!,
Greetings,
Sigurd

**Comment by perevoznyk** [comment]
Nuget package for latest versio 1.8.6 is created and available here or via nuget.org
