### ISSUE TITLE
Housenumber seperate from streetname possible?

### ISSUE THREAD

**Issue by WalterEbbers** [perevoznyk/swelio-sdk#12]
Hi,

I'm currently in the process of updating a project that uses a old version of the EIDNative library to use the swelio framework. 
In this process i saw that streetname and housenumber where combined into one object called "Street" in swelio.

Is there a way to get this data in a seperated form within the framework (Like StreetName and Housenumber objects)?
We use the framework to fill out a form with all the data that is read and streetname and housenumber are seperate in this form. 

I hope it is possible.

Kind regards, 

Walter

**Comment by perevoznyk** [comment]
Added possibility to parse address in v1.18.9
The address is stored on id card as single string and the house number is not separated from street name. I added possibility to parse address and split the house number from the street name by calling Parse() function of Address class

**Comment by WalterEbbers** [comment]
Thank you for the reply and implementation!
