### ISSUE TITLE
Checking PIN code with 5 or more digits

### ISSUE THREAD

**Issue by dnn-itb** [perevoznyk/swelio-sdk#13]
First of all, thank you for developing this sdk!
I'm running into a problem when checking PIN codes having more than 4 digits. Whenever I use Swelio.Engine Card.VerifyPinCode for PIN codes having 5 or more digits it always returns false (when using 4 digit PIN code it works without a problem). I use Swelio.Engine dll version 1.18.8 and Swelio32.dll 1.18.0.0. Does the library prevent in any way the correct verification of 5 digits (or more) PIN codes? Is the length of the PIN code limited to 4 digits when using the VerifyPinCode function? Belgian eID cards accept PIN codes up to 12 digits.

**Comment by perevoznyk** [comment]
Fixed in v1.18.11

**Comment by dnn-itb** [comment]
Thank you for your quick response and for solving the issue! V1.18.11 works without a problem with 5+ digits PIN codes.

**Comment by SANAM2022** [comment]
Hello,
can you please send code in windev to check pin code winth swelio
