### ISSUE TITLE
Encryption.GenerateNonRepudiationSignature always returns null

### ISSUE THREAD

**Issue by bobwalbers** [perevoznyk/swelio-sdk#16]
We have compiled the Signature sample project. 
The method Encryption.GenerateNonRepudiationSignature always returns null. No exception is raised.
The pin code is correct.
We've tested with Encryption.GenerateAuthenticationSignature and this does return null as well.

What could be the reason for this?

**Comment by perevoznyk** [comment]
Sample project fixed. It is necessary now to use SHA256 instead of SHA1. 
The reason was outdated SHA1 usage in the demo project. It is necessary to replace SHA1Managed with SHA256Managed.
