### ISSUE TITLE
New card SHA384

### ISSUE THREAD

**Issue by nicolas-cop** [perevoznyk/swelio-sdk#17]
Hi,

First of all, great sdk :) 

Is there a way to sign with new card with sha384 or the sdk is not yet ready for this?

Many thanks

**Comment by perevoznyk** [comment]
In v1.18.22 I added new class Algorithm which can be used to specify required encryption aloorithm (for new and old cards). This algorithm can be used when calling GenerateNonRepudiationSignature. By default the old cards use SHA256 and new cards SHA384.
