### ISSUE TITLE
New Swelio dll doesn't work with all e-id readers. Old Swelio dll is ok

### ISSUE THREAD

**Issue by NicoJuicy** [perevoznyk/swelio-sdk#19]
I have a similar issue like this: https://github.com/perevoznyk/swelio-pdf/issues/4

When i read an e-id, i have issues reading an older e-id card on some e-id readers. It works on all e-id readers in a previous version of Swelio ( i tested with these [dll's from swelio-pdf](https://github.com/perevoznyk/swelio-pdf/blob/2586992e029a9126a845ea18a6d094e30020caec/PDFSigner/Swelio32.dll) )

The method that fails with the newer Swelio dll's is: 

    Encryption.GenerateNonRepudiationSignature(reader, this.pin, digest, digest.Length)

Is there a way to set the compatibility in some cases to the previous version? I have installed the latest firmware.

**Comment by perevoznyk** [comment]
@NicoJuicy Could you tell me when the old card was issued (year) and if possible the version of applet on this card.

**Comment by NicoJuicy** [comment]
@perevoznyk The id card was issued on 15/10/2018. 
The applet version = 23.

**Comment by perevoznyk** [comment]
The difference between old and new implementation is the used hash algorithm. Starting from v1.18.22 you can choose the hash algoritjm which will be used. For old cards the default algorithm is RSASSA_PKCS1_SHA256 while previously it was RSASSA_PKCS1. I suppose that not all readers support default algorithm, but you can change it to another value for compatibility with the card reader.

**Comment by NicoJuicy** [comment]
@perevoznyk Are you aware of any issues with e-id with the applet version = 24 ( card was issued in 2024)?

Using pdfsigner, it signs the card but says there are signer issues.
