### ISSUE TITLE
Signing document

### ISSUE THREAD

**Issue by Fabsky** [perevoznyk/swelio-sdk#2]
Hello

I wondering if it could be possible to sign document using your library ?
I already have lib to sign PDF, docx etc but I need the certificate from the eID card, and I don't see a way to retrieve it using your lib. So it seems it's not possible. Could you confirm ?

Because I've already check other lib from e-contract or fedict etc. and it seems that it's only java based, or it's SAAS so we need to upload the document to a service, which I don't like. So I search a simple solution where the user could just put his eID and sign a document, using c#.

Thank you for your help
Fabrice

**Comment by perevoznyk** [comment]
1. It is possible to sign documents using swelio library
2. Certificates can be retrieved using SaveCertificate or ReadCertificate methods of Card class
3. I started new project swelio-pdf (https://github.com/perevoznyk/swelio-pdf) for implementation of digital signature using swelio and itextsharp libraries. I have already working prototype, so I will publish code to github soon 

All ideas regarding digital signature implementation are welcome.

**Comment by Fabsky** [comment]
Hello. I know this is quite old but as the project was paused I've implemented the signature only now. Currently in alpha, seems to works fine. Thank your for your library!
