### ISSUE TITLE
Detecting 64bit on a fresh machine seems broken

### ISSUE THREAD

**Issue by GillesDV** [perevoznyk/swelio-sdk#22]
I'm currently on a 64 bit Windows 11 system. When I tried to run the HelloWorld project in C# Samples, I got a BadImageFormatException. 

> An attempt was made to load a program with an incorrect format. (Exception from HRESULT 0x800700B)

I realize it's because the system was trying to load the 32 bit version. See NativeMethods.cs > line ~25 the detection for whether it's a 64 bit or 32 bit seems broken? 

Does the project rely on a system_variable or something? 
Or is something missing in the README?

**Comment by perevoznyk** [comment]
The project was divided into two nuget packages:
https://www.nuget.org/packages/Swelio-x64 x64 version
https://www.nuget.org/packages/Swelio - x32 version

For x64 Windows you need x64 package version.
