### ISSUE TITLE
Dlls in redist folder are not dlls

### ISSUE THREAD

**Issue by yvkevitch** [perevoznyk/swelio-sdk#24]
swelio32.ddl and swelio64.ddl in the redistr folder are not dlls files.

**Comment by perevoznyk** [comment]
The files in Redist folder are **native Windows DLLs** and not .NET Assemblies. You need to distribute both files in addition to Swelio.Engine.dll which is a .NET Assembly. The easiest way is to use https://www.nuget.org/packages/Swelio-x64 or https://www.nuget.org/packages/Swelio (x32 package).
