### ISSUE TITLE
Callback not detecting other card type

### ISSUE THREAD

**Issue by Ledeganck** [perevoznyk/swelio-sdk#3]
Hello,
First, thanks for this great job and to share your development.

I got problem with the card trigger.
Callback event are working has expected with and EID card.
When I use other type of card, it's not working properly.
If it's a card with a ship on it, like a credit card, only event CardRemove is triggered.  CardInsert never trigger with those card.  This is a problem for me because I have to trigger all type of card insertion.
If it's a card without ship, there are no CardInsert and CardRemove.
Can you check if the problem comes from my reader itself or from the code?  If from the code, could you detect insertion and removal of any type of card?

Regards,
G.Ledeganck

**Comment by Ledeganck** [comment]
Hello,
I used different smart card readers and confirm that a card without ship doesn't trigger the Event card Insertion and Removal.
When using a PC/SC tracker, the Insertion and Removal are well triggered.
Regards,
G.Ledeganck

**Comment by perevoznyk** [comment]
fixed in v1.13
