### ISSUE TITLE
Problem while reading my identity card

### ISSUE THREAD

**Issue by kazhhh** [perevoznyk/swelio-sdk#8]
Hi. First of all I want to thank you for your work.

I'm contacting you because everything is working except the readadress function.

here is my structures:

![image](https://user-images.githubusercontent.com/57951683/105735329-dd8e6680-5f33-11eb-9e79-c38b9233a4b2.png)

I can read my Identity and my Picture but not my address. It is returning 0.

Is the problem my address structure?

When I try using the unicode function i get a result but the postal code and municipality are not complete (first characters missing)

Thank you.

**Comment by perevoznyk** [comment]
I am not WinDev specialist, but according to documentation the type "string on" correspends to C like zero ending string. In this case you don't need to add extra character to the end of the string and the size of the strings in the structure declaration will be 
shorter, like "sStreet string on 80",etc..

**Comment by perevoznyk** [comment]
You can also try the latest release https://github.com/perevoznyk/swelio-sdk/releases/tag/v1.18.4
